In [45]:
import numpy as np

In [46]:
from dec.grid1 import Grid_1D
from dec.symbolic import *

In [47]:
g = Grid_1D.periodic(7)
c = Chart(x, )
f = form(0, c, (sin(x),))

In [64]:
fd = f.P(g, True)
(f.lambdify(g.points).dtype,
 g.refine.T[f.degree, fd.isprimal](fd.array).dtype)

(dtype('float64'), dtype('float64'))

In [49]:
f.lambdify(g.points) - g.refine.T[f.degree, fd.isprimal](fd.array)

array([  0.00000000e+00,  -1.78986903e-08,  -2.04463989e-08,
        -6.92135771e-09,   9.96014393e-09,   1.74859931e-08,
         1.25207260e-08,   1.77193889e-15,  -1.25207257e-08,
        -1.74859932e-08,  -9.96014393e-09,   6.92135782e-09,
         2.04463988e-08,   1.78986905e-08])

In [50]:
fd.array - g.refine.U[f.degree, fd.isprimal](f.lambdify(g.points))

array([  0.00000000e+00,   2.04463989e-08,  -9.96014393e-09,
        -1.25207260e-08,   1.25207257e-08,   9.96014393e-09,
        -2.04463988e-08])

In [65]:
from dec.spectral import H, Hinv, S, Sinv

In [60]:
H(np.ones(N))-2*np.pi/N

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [62]:
g.verts.dtype

dtype('float64')