In [24]:
import numpy as np

In [25]:
from dec.grid1 import Grid_1D
from dec.symbolic import *

In [26]:
g = Grid_1D.periodic(7)
c = Chart(x, )
f = form(0, c, (sin(x),))

In [27]:
fd = f.P(g, True)
(f.lambdify(g.points).dtype,
 g.refine.T[f.degree, fd.isprimal](fd.array).dtype)

(dtype('float64'), dtype('float64'))

In [28]:
f.lambdify(g.points)- g.refine.T[f.degree, fd.isprimal](fd.array)

array([  0.00000000e+00,   1.66533454e-16,   0.00000000e+00,
         8.88178420e-16,   0.00000000e+00,   2.22044605e-16,
         0.00000000e+00,   1.70849757e-15,   0.00000000e+00,
        -4.44089210e-16,   0.00000000e+00,  -6.66133815e-16,
         0.00000000e+00,   5.55111512e-17])

In [29]:
fd.array - g.refine.U[f.degree, fd.isprimal](f.lambdify(g.points))

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [30]:
from dec.spectral import H, Hinv, S, Sinv

In [31]:
# The hodge star of ones must be the lengths of the dual edges
N= 10; H(np.ones(N))-2*np.pi/N

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [32]:
g.verts.dtype

dtype('float64')

In [33]:
g = Grid_1D.periodic(11)
f = form(0, c, (cos(3*x),))
(f.H.P(g, True) - f.P(g, False).H).array

array([  5.55111512e-17,   1.66533454e-16,  -3.88578059e-16,
        -1.11022302e-16,  -8.18789481e-16,  -3.33066907e-16,
         1.72084569e-15,   1.66533454e-16,   6.10622664e-16,
        -4.44089210e-16,  -8.88178420e-16])

In [34]:
f = form(1, c, (cos(3*x),))
(f.H.P(g, True) - f.P(g, False).H).array

array([  6.66133815e-16,  -1.66533454e-16,  -2.22044605e-16,
        -1.05471187e-15,  -1.66533454e-15,   9.99200722e-16,
         1.11022302e-15,  -3.10862447e-15,   1.22124533e-15,
        -2.22044605e-16,   8.32667268e-17])